name: Django CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  check_code:
    name: Code Quality Check
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
  
    - name: Build Docker Image
      run: docker build -t github_actions .

    - name: Install Dependencies
      run: |
        pip install --no-cache-dir -r sdlc/requirements.txt
        pip install --no-cache-dir -r app/requirements.txt

    - name: Run Code Quality Checks
      env:
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        DEBUG: ${{ vars.DEBUG }}
        DBNAME: ${{ secrets.DBNAME }}
        DBUSER: ${{ secrets.DBUSER }}
        DBPWD: ${{ secrets.DBPWD }}
        DBHOST: ${{ secrets.DBHOST }}
        DBPORT: ${{ secrets.DBPORT }}
      run: bash sdlc/check_code

  verify_docker:
    name: Verify Docker Image and Container
    runs-on: ubuntu-latest
    needs: check_code

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Build Docker Image
      run: docker build -t github_actions .

    - name: Install Dependencies
      run: |
        pip install --no-cache-dir -r app/requirements.txt

    - name: Run Container Health Check
      env:
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        DEBUG: ${{ vars.DEBUG }}
        DBNAME: ${{ secrets.DBNAME }}
        DBUSER: ${{ secrets.DBUSER }}
        DBPWD: ${{ secrets.DBPWD }}
        DBHOST: ${{ secrets.DBHOST }}
        DBPORT: ${{ secrets.DBPORT }}
      run: python3 app/home/scripts/health_check.py
  
  deploy:
    name: Deploy Project to Docker
    runs-on: ubuntu-latest
    needs: verify_docker

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Build Docker Image
      run: docker build -t github_actions .

    - name: Create .env file
      run: |
        echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> .env
        echo "DEBUG=${{ vars.DEBUG }}" >> .env
        echo "DBNAME=${{ secrets.DBNAME }}" >> .env
        echo "DBUSER=${{ secrets.DBUSER }}" >> .env
        echo "DBPWD=${{ secrets.DBPWD }}" >> .env
        echo "DBHOST=${{ secrets.DBHOST }}" >> .env
        echo "DBPORT=${{ secrets.DBPORT }}" >> .env

    - name: Clone scripts repository
      run: |
        git clone https://github.com/vstrickl/bin.git ~/bin
  
    - name: Deploy Docker Image
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_ACCESS_TOKEN: ${{ secrets.DOCKER_ACCESS_TOKEN }}
        DJANGO_ALLOWED_HOSTS: ${{ secrets.DJANGO_ALLOWED_HOSTS }}
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        DEBUG: ${{ vars.DEBUG }}
        DBNAME: ${{ secrets.DBNAME }}
        DBUSER: ${{ secrets.DBUSER }}
        DBPWD: ${{ secrets.DBPWD }}
        DBHOST: ${{ secrets.DBHOST }}
        DBPORT: ${{ secrets.DBPORT }}
      run: ~/bin/sdlc/deploy